export const JOB_TEXT = {
  form: {
    titleCreate: "Post a New Job Opportunity",
    titleEdit: "Modify Job Listing",
    errorMsg: "Something went wrong. Please check your inputs and try again.",
    jobTitleLabel: "Job Title",
    jobTitlePlaceholder: "e.g., Senior React Developer",
    jobTypeLabel: "Job Type",
    locationLabel: "Location",
    locationPlaceholder: "e.g., Remote, San Francisco, CA",
    minExperienceLabel: "Min Experience (Years)",
    minExperiencePlaceholder: "e.g., 2",
    maxExperienceLabel: "Max Experience (Years)",
    maxExperiencePlaceholder: "e.g., 5",
    minSalaryLabel: "Minimum Annual Salary (INR)",
    minSalaryPlaceholder: "e.g., 600000",
    maxSalaryLabel: "Maximum Annual Salary (INR)",
    maxSalaryPlaceholder: "e.g., 1200000",
    deadlineLabel: "Application Deadline",
    skillsLabel: "Required Technical Skills (comma separated)",
    skillsPlaceholder: "e.g., React, TypeScript, Node.js, Mongoose",
    descriptionLabel: "Detailed Job Description",
    descriptionPlaceholder: "Outline job responsibilities, project scopes, qualifications, and benefits...",
    submitBtnCreate: "Post Job Listing",
    submitBtnEdit: "Update Job listing",
    submittingBtn: "Submitting Listing...",
  },
  filters: {
    header: "Filter Job Openings",
    jobTypeLabel: "Job Type",
    allJobTypesOption: "All Job Types",
    locationLabel: "Location",
    locationPlaceholder: "e.g., Remote, San Francisco",
    minSalaryLabel: "Min Annual Salary (₹)",
    minSalaryPlaceholder: "e.g. 50000",
    maxSalaryLabel: "Max Annual Salary (₹)",
    maxSalaryPlaceholder: "e.g. 150000",
    skillsLabel: "Skills (comma-separated)",
    skillsPlaceholder: "e.g. React, Node",
    resetBtn: "Reset Filters",
    applyBtn: "Apply Filters",
  },
} as const;
