export const CANDIDATE_TEXT = {
  profileForm: {
    nameLabel: "Full Name",
    namePlaceholder: "e.g., Jane Doe",
    titleLabel: "Professional Title",
    titlePlaceholder: "e.g., Senior Full-Stack Engineer",
    experienceLabel: "Years of Experience",
    experiencePlaceholder: "e.g., 5",
    bioLabel: "Biography (minimum 10 characters)",
    bioPlaceholder: "Summarize your professional experience, key accomplishments, and career interests...",
    submitBtn: "Save Details",
    submittingBtn: "Saving Profile...",
    errorMsg: "Failed to update profile. Please try again.",
  },
  profileOverview: {
    avatarFallback: "CA",
    editProfileBtn: "Edit Profile",
    titleLabel: "Title",
    experienceLabel: "Experience",
    notSpecified: "Not Specified",
    yearsSuffix: " Years",
    bioHeader: "Biography",
    noBio: "No biography added yet.",
    skillsHeader: "Skills",
    noSkills: "No skills listed yet.",
    resumeHeader: "Resume",
    resumePdfTitle: "Resume PDF Document",
    resumePdfSubtitle: "Resume is active and attached to job applications.",
    downloadBtn: "Download",
    noResume: "No resume uploaded yet.",
  },
  resumeManager: {
    activeResumeHeader: "Active Resume Document",
    activeResumeSub: "Your profile resume is currently uploaded and visible to recruiters.",
    downloadCurrentBtn: "Download Current PDF",
    uploadNewHeader: "Upload New Resume",
    onlyPdfError: "Only PDF documents are supported.",
    fileSizeError: "File size exceeds 5MB limit.",
    selectFileFirst: "Please select a PDF file first.",
    failedToUpload: "Failed to upload file.",
    readyForUpload: "Ready for upload",
    dragAndDropText: "Drag and drop your PDF here, or ",
    browseText: "browse",
    pdfFilesOnlyLimit: "PDF files only (Max 5MB)",
    submitBtn: "Upload & Update Resume",
    submittingBtn: "Uploading Resume...",
  },
  skillsManager: {
    inputPlaceholder: "e.g., React, TypeScript, GraphQL",
    addSkillBtn: "Add Skill",
    enterSkillError: "Please enter a skill name.",
    skillExistsError: "This skill is already listed.",
    technicalBadgeHeader: (count: number) => `Technical Skill Badges (${count})`,
    noSkillsYet: "No skills added yet. Use the search box above to add skills.",
    saveBtn: "Save Technical Skills",
    savingBtn: "Saving changes...",
  },
  applyModal: {
    confidentialRecruiter: "Confidential Recruiter",
    successHeader: "Application Submitted!",
    successText: (company: string) => `Your details and cover letter have been shared with the recruiter at ${company}.`,
    formTitle: "Job Application Form",
    warningText: (company: string) => `By applying, your saved profile details (Title, Skills, Years of Experience) and your uploaded Resume PDF file will be shared with the recruiter at ${company}.`,
    errorFallback: "Failed to submit application. Please try again.",
    coverLetterLabel: "Cover Letter (minimum 10 characters)",
    coverLetterPlaceholder: "Explain why you are the perfect candidate for this position...",
    cancelBtn: "Cancel",
    submitBtn: "Send Application",
    submittingBtn: "Submitting...",
  },
} as const;
