export const GLOBAL_TEXT = {
  landing: {
    badge: "Connect with Top Recruiting Agencies",
    heading: "Find Your Next Dream Job Today",
    subheading: "Explore open vacancies from industry leaders. Create a profile, upload your resume PDF, and match with recruiters instantly.",
    searchPlaceholderKeyword: "Job title or keywords...",
    searchPlaceholderLocation: "Location (e.g. Remote)...",
    searchPlaceholderSkills: "Skills (e.g. React, Node)...",
    searchBtn: "Search Vacancies",
    metrics: {
      vacanciesCount: "12,000+",
      vacanciesLabel: "Active Vacancies",
      employersCount: "450+",
      employersLabel: "Verified Employers",
      candidatesCount: "80,000+",
      candidatesLabel: "Registered Candidates",
    },
    featuredTitle: "Featured Job Openings",
    featuredSub: "Browse our latest listings matching hot market demands.",
    viewAllJobs: "View All Openings",
    ctaCandidate: {
      badge: "For Candidates",
      title: "Accelerate Your Career",
      desc: "Create a professional profile, manage your technical qualifications, upload your resume PDF, and apply to vacancies with a single click.",
      btn: "Register as Job Seeker",
    },
    ctaRecruiter: {
      badge: "For Recruiters",
      title: "Hire Top Industry Talent",
      desc: "Post job openings, specify technical requirements, manage applicant pipelines, and hire candidates efficiently.",
      btn: "Register as Employer",
    },
  },
  errors: {
    failedToLoadJobs: "Failed to load jobs. Please try refreshing.",
    noFeaturedJobs: "No open job postings available at this time.",
    mustBeLoggedIn: "You must be logged in to view this page.",
  },
  actions: {
    saving: "Saving...",
    saveDetails: "Save Details",
    saveProfile: "Save Profile",
    savingProfile: "Saving Profile...",
    editProfile: "Edit Profile",
    cancel: "Cancel",
    ok: "OK",
    submit: "Submit",
    loading: "Loading...",
  },
} as const;
