export const APPLICATION_TEXT = {
  statusModal: {
    title: "Update Candidate Status",
    subtitle: "Select a status to apply to this candidate application.",
    cancelBtn: "Cancel",
    applyBtn: "Apply Status",
    applyingStatus: "Applying...",
    options: {
      applied: {
        label: "Applied",
        desc: "Initial application state. Resume screening pending.",
      },
      shortlisted: {
        label: "Shortlisted",
        desc: "Candidate meets core criteria. Proceeding to reviews.",
      },
      interviewed: {
        label: "Interviewed",
        desc: "Conducting professional phone screen or technical review.",
      },
      hired: {
        label: "Hired",
        desc: "Offer extended and candidate successfully onboarded.",
      },
      rejected: {
        label: "Rejected",
        desc: "Candidate screening failed or position was filled.",
      },
    },
  },
  drawer: {
    titleRecruiter: "Application Details",
    titleCandidate: "Your Application",
    confidentialRecruiter: "Confidential Recruiter",
    appliedPositionHeader: "Applied Position",
    updateScreeningStatusLabel: "Update Screening Status",
    experienceYearsSuffix: " Years",
    notSpecified: "Not specified",
    biographyHeader: "Biography",
    technicalSkillsHeader: "Technical Skills",
    submittedCoverLetterHeader: "Submitted Cover Letter",
    resumeAttachmentHeader: "Resume Attachment",
    resumeAttachmentSub: "Resume PDF file submitted by candidate.",
    downloadBtn: "Download",
    appliedOnFooter: (dateStr: string, timeStr: string) => `Applied on ${dateStr} at ${timeStr}`,
  },
  table: {
    failedToQuery: "Failed to query applications list.",
    refreshMsg: "Please refresh to try again.",
    noSubmissionsFound: "No Submissions Found",
    emptyCandidateDesc: "You haven't submitted any job applications yet. Find open vacancies to apply!",
    emptyRecruiterDesc: "No candidates have submitted applications for this position yet.",
    findVacanciesBtn: "Find Vacancies",
    headers: {
      position: "Position",
      company: "Company",
      candidate: "Candidate",
      experience: "Experience",
      dateApplied: "Date Applied",
      status: "Status",
      actions: "Actions",
    },
    deletedVacancy: "Deleted Vacancy",
    detailsBtn: "Details",
    screenBtn: "Screen",
    updateStatusTooltip: "Update Status",
    yearsExperienceSuffix: " Years Experience",
    statusMobileBtn: "Status",
  },
} as const;
