export const AUTH_TEXT = {
  login: {
    title: "Sign In",
    subtitle: "Enter your details below to log in to your account",
    successMsg: "Registration successful! Please sign in with your credentials.",
    resetSuccessMsg: "Password has been reset successfully! Please sign in with your new credentials.",
    errorMsg: "Invalid credentials, please try again.",
    emailLabel: "Email Address",
    emailPlaceholder: "name@example.com",
    passwordLabel: "Password",
    passwordPlaceholder: "••••••••",
    showPassword: "Show password",
    hidePassword: "Hide password",
    signInBtn: "Sign In",
    signingInBtn: "Signing In...",
    noAccount: "Don't have an account? ",
    createAccount: "Create account",
  },
  register: {
    title: (role: string) => `Sign Up as ${role}`,
    subtitleCandidate: "Create an account to browse and apply for jobs",
    subtitleRecruiter: "Create an account to post job openings and hire talent",
    errorMsg: "Registration failed. Please try again.",
    nameLabel: "Full Name",
    namePlaceholder: "John Doe",
    emailLabel: "Email Address",
    emailPlaceholder: "name@example.com",
    passwordLabel: "Password",
    passwordPlaceholder: "••••••••",
    createAccountBtn: "Create Account",
    creatingAccountBtn: "Creating Account...",
    hasAccount: "Already have an account? ",
    signInLink: "Sign in",
  },
  forgotPassword: {
    title: "Forgot Password",
    subtitle: "Enter your email address and we'll send you a link to reset your password",
    emailLabel: "Email Address",
    emailPlaceholder: "name@example.com",
    submitBtn: "Send Reset Link",
    submittingBtn: "Sending Link...",
    successMsg: "A password reset link has been sent to your email address.",
    backToLogin: "Back to Sign In",
  },
  resetPassword: {
    title: "Reset Password",
    subtitle: "Enter your new password below to secure your account",
    passwordLabel: "New Password",
    passwordPlaceholder: "••••••••",
    confirmPasswordLabel: "Confirm New Password",
    confirmPasswordPlaceholder: "••••••••",
    submitBtn: "Reset Password",
    submittingBtn: "Resetting Password...",
    successMsg: "Your password has been successfully reset.",
    backToLogin: "Back to Sign In",
    showPassword: "Show password",
    hidePassword: "Hide password",
  },
} as const;
